[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "citesphere-connector"
version = "1.0.0"
authors = [
    {name = "Digital Innovation Group", email = "diging@asu.edu"},
    {name = "Julia Damerow", email = "jdamerow@asu.edu"},
]
maintainers = [
    {name = "Julia Damerow", email = "jdamerow@asu.edu"},
]
description = "Connect to Citesphere, an application that enables superior management of Zotero citations"
readme = "README.md"
requires-python = ">=3.8"
license = "MPL 2.0"
license-files = ["LICENSE"]
keywords = ["cite", "diging", "citesphere", "sphere", "zotero"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Research Software Engineers, Researchers, Data Scientists, Developers",
  "Topic :: Reserach Software Engineering :: Citation Manager",
  "Programming Language :: Python",
]

[tool.hatch.build]
include = ["src/*"]
