[project]
name = "citesphere-connector"
version = "1.0.0"
dependencies = [
    "cfgv",
    "distlib",
    "filelock",
    "identify",
    "nodeenv",
    "platformdirs",
    "pre_commit",
    "PyYAML",
    "ruff",
    "virtualenv",
]
requires-python = ">= 3.9"
authors = [
    {name = "Julia Damerow", email = "jdamerow@asu.edu"},
    {name = "Julian Ophals", email = "jophals@asu.edu"},
    {name = "Vishnu Vardhan Sanikommu", email = "vrsaniko@asu.edu"},
    {name = "Ajay Yadav", email = "ayadav55@asu.edu"},
]
maintainers = [
    {name = "Julia Damerow", email = "jdamerow@asu.edu"},
    {name = "Julian Ophals", email = "jophals@asu.edu"},
]
description = "Connect to Citesphere, an application that enables superior management of Zotero citations"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["cite", "diging", "citesphere", "sphere", "zotero"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Research Software Engineers, Researchers, Data Scientists, Developers",
  "Topic :: Reserach Software Engineering :: Citation Manager",
  "Programming Language :: Python",
]

[project.urls]
"Citesphere API" = "https://documenter.getpostman.com/view/19365454/UVeMJiyx"
